spring:
  datasource:
    url: jdbc:mysql://192.168.1.19:3306/cxd?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    database: 0
    host: 192.168.1.19
    port: 6379
    password: root
    timeout: 15000
    jedis:
      pool:
        max-idle: 6